name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint || echo "SwiftLint finished with warnings"

# Uncomment if unit tests are ready
#      - name: Run Unit Tests
#        run: |
#          xcodebuild clean test \
#            -project MasterApp.xcodeproj \
#            -scheme MasterApp \
#            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
